### ISSUE TITLE
Duplicate upload for custom  fields (images)

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/caldera-custom-fields#21] opened 2017-05-26 11:52 UTC
Using the master branch of Caldera Custom Fields, images that are used with the Save As Post Type as a custom field is uploading twice.

To recreate -

1. Create a Caldera Form that uses Save As Post Type Processor.
2. In the processor do not set the upload field to the featured image so it's added to custom field
3. Ensure 'Add to Library' is enabled on the upload field.

**Comment by Shelob9** [comment] 2017-05-26 18:39
Closing as dupe of #17 and #20

**Closed by Shelob9** 2017-05-26 18:39 UTC
